# Generated by Django 4.2.2 on 2023-10-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Подробности'),
        ),
    ]
