# Generated by Django 4.2.2 on 2023-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_purchase_is_delivered_remove_purchase_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Адрес доставки'),
        ),
    ]
