# Generated by Django 4.2.2 on 2023-10-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_purchase_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
    ]
